name: MLflow CI Pipeline - Heart Disease

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 \
                      scikit-learn==1.5.2 \
                      pandas==2.2.3 \
                      numpy==1.26.4 \
                      matplotlib==3.9.2 \
                      dagshub==0.3.9

      - name: Set MLflow Tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/mlsystem-heart-disease.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=${{ secrets.DAGSHUB_USERNAME }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Run mlflow project
        run: |
          mlflow run MLProject/ \
            -P n_estimators=100 \
            -P max_depth=5 \
            -P min_samples_split=2 \
            --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          echo "Menunggu DagsHub sync..."
          sleep 30
          RUN_ID=$(python -c "
          import mlflow, os, time
          mlflow.set_tracking_uri(os.environ['MLFLOW_TRACKING_URI'])
          client = mlflow.tracking.MlflowClient()
          exp = client.get_experiment_by_name('Heart Disease Classification')

          for i in range(5):
              runs = client.search_runs(
                  experiment_ids=[exp.experiment_id],
                  order_by=['start_time DESC'],
                  max_results=10
              )
              for run in runs:
                  if 'accuracy' in run.data.metrics:
                      print(run.info.run_id)
                      exit()
              print(f'Percobaan {i+1}: belum ada run valid, tunggu 15 detik...')
              time.sleep(15)
          raise Exception('Tidak ada run valid!')
          ")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-model-artifacts
          path: |
            mlruns/
            confusion_matrix.png

      - name: Check downloaded model
        run: |
          MODEL_PATH=$(cat model_path.txt)

          echo "=== MLmodel ==="
          cat "$MODEL_PATH/MLmodel"

          echo ""
          echo "=== conda.yaml ==="
          cat "$MODEL_PATH/conda.yaml"

      - name: Build Docker Model
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          echo "Download model dari DagsHub..."
          python -c "
          import mlflow, os
          mlflow.set_tracking_uri(os.environ['MLFLOW_TRACKING_URI'])
          model_uri = f\"runs:/${{ env.RUN_ID }}/model\"
          local_path = mlflow.artifacts.download_artifacts(model_uri)
          print(f'Model didownload ke: {local_path}')
          with open('model_path.txt', 'w') as f:
              f.write(local_path)
          "
          MODEL_PATH=$(cat model_path.txt)
          echo "Building Docker dari lokal: $MODEL_PATH"
          mlflow models build-docker \
            -m "$MODEL_PATH" \
            -n "heart-disease-model" \
            --env-manager local

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: |
          docker tag heart-disease-model \
            ${{ secrets.DOCKER_USERNAME }}/heart-disease-model:latest
          docker tag heart-disease-model \
            ${{ secrets.DOCKER_USERNAME }}/heart-disease-model:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/heart-disease-model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/heart-disease-model:${{ github.sha }}

      - name: Complete job
        run: |
          echo "================================================"
          echo "  CI Pipeline selesai!"
          echo "  Run ID : ${{ env.RUN_ID }}"
          echo "  Image  : ${{ secrets.DOCKER_USERNAME }}/heart-disease-model:latest"
          echo "================================================"